### ISSUE TITLE
pygame not installing during setup.py

### ISSUE THREAD

**Issue by Cucumbear** [c0redumb/midi2vjoy#1]
Hi,
I am a beginner cmd user and have problems with installing. I tried to install on python 3.7.0 win 10 using cmd prompt via "setup.py install"  while being in correct directory where I have unzipped the master branch.
After running the installation(finally) an error occurred and I think that pygame has failed to download or install, so I've tried to install manually but that didn't seemto work either. I'm including the "print" of cmd after installation: 

> running install
> running bdist_egg
> running egg_info
> writing midi2vjoy.egg-info\PKG-INFO
> writing dependency_links to midi2vjoy.egg-info\dependency_links.txt
> writing entry points to midi2vjoy.egg-info\entry_points.txt
> writing requirements to midi2vjoy.egg-info\requires.txt
> writing top-level names to midi2vjoy.egg-info\top_level.txt
> package init file 'midi2vjoy\__init__.py' not found (or not a regular file)
> reading manifest file 'midi2vjoy.egg-info\SOURCES.txt'
> writing manifest file 'midi2vjoy.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_py
> creating build\bdist.win-amd64\egg
> creating build\bdist.win-amd64\egg\midi2vjoy
> copying build\lib\midi2vjoy\midi2vjoy.py -> build\bdist.win-amd64\egg\midi2vjoy
> byte-compiling build\bdist.win-amd64\egg\midi2vjoy\midi2vjoy.py to midi2vjoy.cpython-37.pyc
> creating build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying midi2vjoy.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
> creating 'dist\midi2vjoy-0.1-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
> removing 'build\bdist.win-amd64\egg' (and everything under it)
> Processing midi2vjoy-0.1-py3.7.egg
> removing 'c:\users\cucumbear\appdata\local\programs\python\python37\lib\site-packages\midi2vjoy-0.1-py3.7.egg' (and everything under it)
> creating c:\users\cucumbear\appdata\local\programs\python\python37\lib\site-packages\midi2vjoy-0.1-py3.7.egg
> Extracting midi2vjoy-0.1-py3.7.egg to c:\users\cucumbear\appdata\local\programs\python\python37\lib\site-packages
> midi2vjoy 0.1 is already the active version in easy-install.pth
> Installing midi2vjoy-script.py script to C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\Scripts
> Installing midi2vjoy.exe script to C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\Scripts
> 
> Installed c:\users\cucumbear\appdata\local\programs\python\python37\lib\site-packages\midi2vjoy-0.1-py3.7.egg
> Processing dependencies for midi2vjoy==0.1
> Searching for pygame
> Reading https://pypi.python.org/simple/pygame/
> C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
>   warn=(impl == 'cp')):
> C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
>   warn=(impl == 'cp')):
> Downloading https://files.pythonhosted.org/packages/ba/96/82495010a3daf94f579c6fc60a2466212057a3db38ce7927f01f32941968/pygame-1.9.4.dev0.tar.gz#sha256=2566eb6284676e3ceeeb4c078629bafe7fce4712a8ced8af4593f2e7e1a1f445
> Best match: pygame 1.9.4.dev0
> Processing pygame-1.9.4.dev0.tar.gz
> Writing C:\Users\CUCUMB~1\AppData\Local\Temp\easy_install-c2kroilz\pygame-1.9.4.dev0\setup.cfg
> Running pygame-1.9.4.dev0\setup.py -q bdist_egg --dist-dir C:\Users\CUCUMB~1\AppData\Local\Temp\easy_install-c2kroilz\pygame-1.9.4.dev0\egg-dist-tmp-1023hdap
> 
> 
> WARNING, No "Setup" File Exists, Running "config.py"
> Using WINDOWS configuration...
> 
> Path for SDL not found.
> Too bad that is a requirement! Hand-fix the "Setup"
> Path for FONT not found.
> Path for IMAGE not found.
> Path for MIXER not found.
> Path for PNG not found.
> Path for JPEG not found.
> Path for PORTMIDI not found.
> Path for COPYLIB_tiff not found.
> Path for COPYLIB_z not found.
> Path for COPYLIB_vorbis not found.
> Path for COPYLIB_ogg not found.
> 
> If you get compiler errors during install, doublecheck
> the compiler flags in the "Setup" file.
> 
> 
> Continuing With "setup.py"
> Error with the "Setup" file,
> perhaps make a clean copy from "Setup.in".
> Traceback (most recent call last):
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
>     yield saved
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
>     yield
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
>     _execfile(setup_script, ns)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
>     exec(code, globals, locals)
>   File "C:\Users\CUCUMB~1\AppData\Local\Temp\easy_install-c2kroilz\pygame-1.9.4.dev0\setup.py", line 165, in <module>
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\extension.py", line 171, in read_setup_file
>     line = expand_makefile_vars(line, vars)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\sysconfig.py", line 407, in expand_makefile_vars
>     s = s[0:beg] + vars.get(m.group(1)) + s[end:]
> TypeError: can only concatenate str (not "NoneType") to str
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "setup.py", line 16, in <module>
>     'midi2vjoy=midi2vjoy.midi2vjoy:main',
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 67, in run
>     self.do_egg_install()
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
>     cmd.run()
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 412, in run
>     self.easy_install(spec, not self.no_deps)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 654, in easy_install
>     return self.install_item(None, spec, tmpdir, deps, True)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 701, in install_item
>     self.process_distribution(spec, dist, deps)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 746, in process_distribution
>     [requirement], self.local_index, self.easy_install
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
>     replace_conflicting=replace_conflicting
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 1057, in best_match
>     return self.obtain(req, installer)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 1069, in obtain
>     return installer(requirement)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
>     return self.install_item(spec, dist.location, tmpdir, deps)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
>     dists = self.install_eggs(spec, download, tmpdir)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 884, in install_eggs
>     return self.build_and_install(setup_script, setup_base)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 1152, in build_and_install
>     self.run_setup(setup_script, setup_base, args)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\command\easy_install.py", line 1138, in run_setup
>     run_setup(setup_script, args)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
>     raise
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
>     yield
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
>     saved_exc.resume()
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 141, in resume
>     six.reraise(type, exc, self._tb)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
>     yield saved
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
>     yield
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
>     _execfile(setup_script, ns)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
>     exec(code, globals, locals)
>   File "C:\Users\CUCUMB~1\AppData\Local\Temp\easy_install-c2kroilz\pygame-1.9.4.dev0\setup.py", line 165, in <module>
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\extension.py", line 171, in read_setup_file
>     line = expand_makefile_vars(line, vars)
>   File "C:\Users\Cucumbear\AppData\Local\Programs\Python\Python37\lib\distutils\sysconfig.py", line 407, in expand_makefile_vars
>     s = s[0:beg] + vars.get(m.group(1)) + s[end:]
> TypeError: can only concatenate str (not "NoneType") to str

**Comment by Cucumbear** [comment]
Found solution.

**Comment by DarkFox** [comment]
Would you mind sharing with the rest of the class?
