### ISSUE TITLE
Error initializing virtual joysticks after windows reinstall

### ISSUE THREAD

**Issue by MinecrackTyler** [c0redumb/midi2vjoy#12]
Had to reinstall windows because update bricked computer and stuff and after making it through installing python and everything I found that this just doesn't work anymore.
No matter what I do I just see Error initializing virtual joysticks and then maybe some errors or maybe it just stops
Any Idea what I can do?

**Comment by c0redumb** [comment]
No idea. Sorry.

**Comment by MinecrackTyler** [comment]
It's ok, found an alternative for now
