### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by Pomax** [c0redumb/midi2vjoy#19]
Is this library technically still being maintained? (just wondering if it'll work on Windows 10 now that python 2.7 no longer exists).

There don't appear to be installation instructions so I just downloaded the code, and run `python setup.py`, which does nothing other that generate this to stdout:

```
> python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by c0redumb** [comment]
It seems that your pull request has fixed the issue you raised. Sorry I haven't had time to maintain this for a while. Let me see if I can find some time to do it.

**Comment by Pomax** [comment]
Aye, I haven't used a setup.py in probably over a decade now, but if I can google for it I figured I might as well file a PR to help someone else not needing to (re)figure it out =)
